# Configuration file for the project

# API keys and tokens
api_keys:
  nasdaq: YOUR_NASDAQ_API_KEY
  yfinance: YOUR_YFINANCE_API_KEY

# Directories
directories:
  tickers: data/tickers.csv
  quotes: data/quotes/

# Date formats
date_formats:
  default: '%Y-%m-%d'

# Download parameters
download_parameters:
  max_ipo_year: 3
  ticker_expiration_days: 90
  quotes_expiration_days: 30
  start_date: '1980-01-01'
  min_cap: 500000000  # minimum company capitalization, USD
  min_price: 3  # minimum price of one share, USD
  max_price: 10000  # maximum price of one share, USD
  name_stop_words:
    - Notes
    - Subordinated
    - Fixed
    - '%'
    - Convertible
  download_batch_size: 30

# Headers for API requests
api_headers:
  nasdaq:
    authority: api.nasdaq.com
    accept: 'application/json, text/plain, */*'
    user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
    origin: 'https://www.nasdaq.com'
    sec-fetch-site: 'same-site'
    sec-fetch-mode: 'cors'
    sec-fetch-dest: 'empty'
    referer: 'https://www.nasdaq.com/'
    accept-language: 'en-US,en;q=0.9'
  # Add headers for other APIs as needed

# Other configurations
# ...
