# -------------------------------- TICKERS_DOWNLOADER CONFIG -------------------------------

# File path to save tickers
path: data/tickers.csv

# Date format to show in the date columns of dataframes
date_format: '%Y-%m-%d'

# Filter the main parameters
filter:
  years_from_ipo: 3             # Minimum number of years since the company's IPO to consider
  expiration_days: 90           # Update ticker info every {x} days
  min_price: 3                  # Minimum price of one share, USD
  max_price: 10000              # Maximum price of one share, USD
  stop_words:                   # List of stop-words in the company name to filter out
    - Notes
    - Subordinated
    - Fixed
    - '%'
    - Convertible

# Update tickers dataframe columns
columns:
    delete:                     # Delete columns from the downloaded dataframe
        - netchange
        - pctchange
        - url
    rename:                     # Rename columns using standard rules
        lastsale: price
        ipoyear: ipoYear
    add:                        # Add columns with default value None (will be updated later)
        - pe
        - beta
        - shortRatio
        - isin
    add_datetype:               # Add datetime columns with default value NaT (will be updated later)
        - quotesStarted
        - quotesUpdated
        - rowUpdated
    apply_types:                # Column types
        symbol: 'string'
        isin: 'string'
        name: 'string'
        price: 'float'
        volume: 'int'
        marketCap: 'int'
        ipoYear: 'int'
        pe: 'float'
        beta: 'float'
        shortRatio: 'float'
        country: 'string'
        sector: 'string'
        industry: 'string'
        quotesStarted: 'datetime64[ns]'
        quotesUpdated: 'datetime64[ns]'
        rowUpdated: 'datetime64[ns]'
    new_order:                      # Reorder columns before saving the dataframe to a file
        - symbol
        - isin
        - name
        - price
        - volume
        - marketCap
        - ipoYear
        - pe
        - beta
        - shortRatio
        - country
        - sector
        - industry
        - quotesStarted
        - quotesUpdated
        - rowUpdated

# NASDAQ API configuration and web requests params
download:
    batch_size: 30              # Batch size for downloading data at one time
    params:                     # API params for downloading
        - - letter
          - '0'
        - - download
          - 'true'
    headers:                    # Request headers for downloading
        authority: api.nasdaq.com
        accept: 'application/json, text/plain, */*'
        user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
        origin: 'https://www.nasdaq.com'
        sec-fetch-site: 'same-site'
        sec-fetch-mode: 'cors'
        sec-fetch-dest: 'empty'
        referer: 'https://www.nasdaq.com/'
        accept-language: 'en-US,en;q=0.9'