# -------------------------------- QUOTES_DOWNLOADER CONFIG --------------------------------

# File paths to save downloaded files
path: data/quotes/              # Directory to save files with quotes of shares. Filename format: {SYMBOL}.csv

min_history_years: 3            # Minimum years of quotes history to approve saving quotes file.
date_format: '%Y-%m-%d'         # Date format to show in the date columns of dataframes
expiration_days: 30             # Update quotes every {x} days

trade_value_threshold: 50       # Minimum average trade value in millions USD to start saving quotes history

# Update quotes dataframe columns
columns:
    delete:                     # Delete columns from the downloaded dataframe
        - 'Adj Close'
    rename:                     # Rename columns using standard rules
        Open: open
        High: high
        Low: low
        Close: close
        Volume: volume
        Dividends: dividends
        Stock Splits: splits
    apply_types:                # Column types
        open: float
        high: float
        low: float
        close: float
        volume: int
        dividends: float
        splits: float

# Batch size for downloading data at one time
batch_size: 30
