# -------------------------------- QUOTES_DOWNLOADER CONFIG --------------------------------

# File paths to save downloaded files
path: data/quotes/        # Directory to save files with quotes of shares. Filename format: {SYMBOL}.csv

# Date format to show in the date columns of dataframes
date_format: '%Y-%m-%d'
expiration_days: 30           # Update quotes every {x} days

# Update quotes dataframe columns
columns:
    delete:                     # Delete columns from the downloaded dataframe
        - 'Adj Close'
    rename:                     # Rename columns using standard rules
        Open: open
        High: high
        Low: low
        Close: close
        Volume: volume
        Dividends: dividends
        Stock Splits: splits
    apply_types:                # Column types
        open: float
        high: float
        low: float
        close: float
        volume: int
        dividends: float
        splits: float

# Batch size for downloading data at one time
batch_size: 30
